### ISSUE TITLE
Error: _aureliaPal.DOM.createElement is not a function

### ISSUE THREAD

**Issue by ppn2** [MeirionHughes/gulp-aurelia-template-lint#6]
This is the first time I am using this tool. I think it is going to be very useful. I hope at some point if you could integrate with tools like Visual Studio Code (intellisense, linting etc), it will enhance the utility many times more.

Unfortunately on my first attempt, I encountered following error. I am using latest version of aurelia and latest version of the lint. Not sure what I am doing wrong, any help will be appreciated.

[14:03:18] Using gulpfile C:\Test\gulpfile.js
[14:03:18] Starting 'au-lint'...
[14:03:18] 'au-lint' errored after 14 ms
[14:03:18] Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4431:29)
    at new SVGAnalyzer (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-binding\dist\commonjs\aurelia-binding.js:4440:9)
    at Object.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:415:12)
    at InvocationHandler.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:585:39)
    at Object.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:445:103)
    at InvocationHandler.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:585:39)
    at Object.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:439:55)
    at InvocationHandler.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\node_modules\aurelia-pal\dist\commonjs\aurelia-pal.js:36:11)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:656:13)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:585:39)
    at Object.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:445:103)
    at InvocationHandler.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:585:39)
    at Object.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:439:55)
    at InvocationHandler.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:392:166)
    at Container.invoke (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:654:23)
    at StrategyResolver.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:133:35)
    at Container.get (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\node_modules\aurelia-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:585:39)
    at SyntaxRule.ASTBuilder (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\dist\ast.js:11:47)
    at SyntaxRule (C:\Test\node_modules\gulp-aurelia-template-lint\node_modules\aurelia-template-lint\dist\rules\syntax.js:12:14)

C:\Test>

**Comment by MeirionHughes** [comment]
looks like its not loaded `pal-nodejs` I will upgrade everything to use the actual 1.0.0 release. I think everything is still on the RC.

**Comment by MeirionHughes** [comment]
I've pushed 0.9 for gulp-aurelia-template-lint and aurelia-template-lint; this should bump all dependencies to aurelia ^1.0.0 apart from that I think you will need node >= 5 and npm >= 3 and it should be good.

**Comment by ppn2** [comment]
Thanks @MeirionHughes. I did not pay attention that node >= 5 is required. After I did that and upgraded to latest version it seems to be working fine.

I did notice one thing though. lint provides a warning that "WARNING: replaceable attribute is obsolete". However I think that replaceable was taken out in RC but added back in RTM. So it should not come up as warning. please confirm.

**Comment by MeirionHughes** [comment]
oh was it? odd I thought they replaced it with `slot`. [I will ask](http://stackoverflow.com/questions/38838725/is-replaceable-attribute-obsolete-in-aurelia-1-0) 

You can reconfigure the options for that btw: https://github.com/MeirionHughes/aurelia-template-lint#usage 
oh was it? odd I thought they replaced it with `slot`. [I will ask](http://stackoverflow.com/questions/38838725/is-replaceable-attribute-obsolete-in-aurelia-1-0) 

You can reconfigure the options for that btw: https://github.com/MeirionHughes/aurelia-template-lint#usage 

Still very much alpha, quite a lot of the static type checking is a bit hairy, getting there slowly; if you notice something you think is wrong [feel free to raise an issue here](https://github.com/MeirionHughes/aurelia-template-lint/issues)

Closing this as you solved your problem. :)

**Comment by ppn2** [comment]
Thanks @MeirionHughes. I did see some issue. Opening new ticket.
